// Generated by convert-images.cjs — do not edit by hand.
export type ShrineImageMeta = { w: number; h: number; variants: number[] };
export const shrineManifest: Record<string, ShrineImageMeta> = {
  "kanna-cu1": {
    "w": 718,
    "h": 718,
    "variants": [
      320,
      480,
      640
    ]
  },
  "kanna-cu2": {
    "w": 480,
    "h": 480,
    "variants": [
      320
    ]
  },
  "kanna-fa1": {
    "w": 640,
    "h": 640,
    "variants": [
      320,
      480
    ]
  },
  "kanna-fa2": {
    "w": 736,
    "h": 736,
    "variants": [
      320,
      480,
      640
    ]
  },
  "kanna-oa1": {
    "w": 800,
    "h": 789,
    "variants": [
      320,
      480,
      640
    ]
  },
  "kanna-oa2": {
    "w": 564,
    "h": 564,
    "variants": [
      320,
      480
    ]
  },
  "kanna1": {
    "w": 721,
    "h": 720,
    "variants": [
      320,
      480,
      640
    ]
  },
  "kanna2": {
    "w": 720,
    "h": 720,
    "variants": [
      320,
      480,
      640
    ]
  },
  "kanna3": {
    "w": 800,
    "h": 1131,
    "variants": [
      320,
      480,
      640
    ]
  },
  "rossi-d1": {
    "w": 736,
    "h": 736,
    "variants": [
      320,
      480,
      640
    ]
  },
  "rossi-d2": {
    "w": 736,
    "h": 736,
    "variants": [
      320,
      480,
      640
    ]
  },
  "rossi-fa1": {
    "w": 736,
    "h": 1039,
    "variants": [
      320,
      480,
      640
    ]
  },
  "rossi-fa2": {
    "w": 735,
    "h": 1065,
    "variants": [
      320,
      480,
      640
    ]
  },
  "rossi1": {
    "w": 736,
    "h": 736,
    "variants": [
      320,
      480,
      640
    ]
  },
  "rossi2": {
    "w": 736,
    "h": 735,
    "variants": [
      320,
      480,
      640
    ]
  },
  "rossi3": {
    "w": 736,
    "h": 735,
    "variants": [
      320,
      480,
      640
    ]
  },
  "rossi4": {
    "w": 736,
    "h": 736,
    "variants": [
      320,
      480,
      640
    ]
  }
};
